# Generated by Django 5.0.6 on 2024-09-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loyalty_points',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
