# Generated by Django 5.1.1 on 2024-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('perfumes', 'Perfumes'), ('vaselines', 'Vaselines'), ('bodysprays', 'Body Sprays')], max_length=20),
        ),
    ]
